### ISSUE TITLE
Add the way in latex to put metadata regarding the zone directly in the pdf to be read by the app to setup the exam zone in app automatically

### ISSUE THREAD

**Issue by barais** [correctexam/corrigeExamFront#219]

**Comment by arnobl** [comment]
Good idea.
Have to invistigate: https://tex.stackexchange.com/questions/495250/can-i-add-more-metadata-to-my-pdf
in particular `xmp-metadata`
that permits to code `\pdfinfo{/Subtitle (text)}`

But I do not think it is possible to get the correct position of the questions (their bounding boxes).

**Comment by barais** [comment]
Perfect
