### ISSUE TITLE
Bug when comparing "similar results" with questions comprising 2 areas

### ISSUE THREAD

**Issue by jbourcie** [correctexam/corrigeExamFront#239]
When we compare similar results on a question with 2 areas we see 2 times the same page.

**Comment by barais** [comment]
@jbourcie could you provide an example in sharing the url that illustrate the bug. I am not able to reproduce this bug

**Comment by barais** [comment]
Got it sorry 
https://correctexam.github.io/corrigeExamFront/comparemark/124/13694
