### ISSUE TITLE
Post processing exam : tag "very good answers" as a post correcting step 

### ISSUE THREAD

**Issue by jbourcie** [correctexam/corrigeExamFront#240]
It would be great to have a functionality when you finish correcting an exam which allows you to view all the top mark answer for each question and select the best one to generate the "ideal correction"

**Comment by barais** [comment]
:+1: 
Easy to do I will manage it

**Comment by barais** [comment]
link to #46 . If we could do the sorting per question, you can next open best answers easily and tag very good answers

**Comment by barais** [comment]
As I fix #46, it could be done through the statistic view. You can select a question, order by note for this question and one of the best sheet for this question. When you are there, you can view all the sheet with the same grade and select if one could be flagged as a best answer. 
@jbourcie Ok for you ?

**Comment by jbourcie** [comment]
It would be great if the sorting by note function worked :) @barais
