### ISSUE TITLE
Navigating through questions automatically mark them with 0

### ISSUE THREAD

**Issue by arnobl** [correctexam/corrigeExamFront#27]
When navigating through questions, the app automatically marks them with 0 so that we cannot determine whether those questions are really marked. Maybe questions should be unrated until the user clicks on marks. This also prevents to get the first unrated questions.
To discuss.

**Comment by arnobl** [comment]
It seems that navigating through questions sends REST POST query `https://api.gradescope.barais.fr/api/student-responses`.
Maybe this is useless as queries are sent when interacting with the marking UI elements.

**Comment by barais** [comment]
Yes we have to design the grade widget to force user to interact with it even if it wants to put a 0. Any ideas ?
