### ISSUE TITLE
Importing a student list from libreoffice did nothing 

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#289]
Steps to reproduce:

Open a spreadsheet containing a list of students with the desired header.
Use Control-C / Control V to copy-paste into the student list in the top-left
empty cell in the Correct Exam student list.

Expected behavior: the students are added

Actual behavior : nothing

On the other hand, this worked smoothly when copy-pasting from that same spreadsheet
after importing it into NextCloud/OnlyOffice.

I compared the end result of copy-pasting into a text editor, and noticed no visible difference
between copying from libreoffice or OnlyOffice (same tab separated value representation)
(did not try with a diff though).

Browser: firefox and chromium.  
OS: Ubuntu 22.04

Btw: it was not clear to me whether:
- it was necessary to include the header line in the copy-paste
- whether the labels in that header line are relevant
- how the column mapping was done
I assume: the header line can be ignored. The columns should be in the following order ine/last/first/mail/group to ensure the proper column mapping. Maybe the doc / online hints could insist on these.

Thanks!

**Comment by barais** [comment]
I will improve the feedback, and try to reproduce. (Strange: it works for me from libreoffice  with the same OS;). It is a new feature, I had to replace the previous component to import that use a non-open-source widget (handsontable) #273

**Comment by nthiery** [comment]
I just tried again for my new exam. It sounds like the point is not about where the
data comes from (OpenOffice, ...), but about the number of columns: since we use
groups of students for the grading, I don't have a group column. After adding a fake
column with X as group for all students, copy-pasting did work.

I guess I had another column last time when I copy pasted from NextCloud?

So presumably this ticket can be closed. Sorry for the noise! It would be nice however
to get some feedback when copy-paste is refused, due e.g. to wrong number of columns.

**Comment by barais** [comment]
Thanks for the feedback

**Comment by acherm** [comment]
I have similar feedbacks. 
The import of data is counterintuitive, but actually working! 

You really need to have values for all column. And I used the same strategy, faking some values for IEN or groups...
But from an HCI point of view, it's not so straightforward to grasp. 
You have to copy and paste starting from IEN. 

Another counterintuitive aspect is the "Import"... 
I was thinking, cool I can upload an xls (like in the template!).
But "import" does not mean this. 
It means once you have copied and pasted values, then you validate and import. 
There is no import from file, and it would be a cool feature! 

Actually it can resolve most of the problems: import an xls like file, and that's it. 
Edit and validate then.

**Comment by nthiery** [comment]
For information: @hivert just got the same issue. I gave him the trick to add a fake column :-)
