### ISSUE TITLE
Suggestions for commenting

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#336]
Misc:
- [x] #368
- [x] Set the pen as default tool: it's presumably the one that is used most (but I may be wrong)
- [x] When switching to the whole page view, let <kbd>Esc</kbd> exit back.
- [x] Vertical space permitting, display a bit of the sheet around the question box (possibly with a
       frame to highlight the box itself), in case the student has overflowed the box.

Applying comments:
- [x] Provide default keyboard shortcuts for toggling each comment according to the order in which they are
  listed; e.g <kbd>1</kbd>, <kbd>2</kbd>, etc. Display the shortcut next to the comment.
- [x] Flashing the screen when adding/removing a comment is tiring for
  the eyes. Do nothing, or just flash the ditto comment?
- [x] #419
  student when no comment applies, but the answer does not either
  deserves "excellent".
- [x] Ability to attach a comment to a specific spot or rectangle in the sheet to point the student to the cool/faulty part of their answer.  

Comment panel:
- [x] #431
  them. Possibly update the keyboard shortcut accordingly (see above).

Creating and editing comments: 
- [x] #464
- [x] When editing comment titles or descriptions: remap
  <kbd>Ctrl</kbd>+arrow to normal text editing shortcuts (move by
  words, ...).
- [x] When editing a comment title: let <kbd>return</kbd> validates
  the title
- [x] When editing the title or number of stars: clicking outside of
  the zone validates and releases the focus
- [x] #432
  how many times the comment is currently used in the copies.

Scoring:
- [x] for negative comments: let the number of points be numeric, or
  'all', meaning removing all points. Use cases: if the total number
  of points for the question is changed later on, the comment need not
  be updated. If the comment is added to all questions, the number of
  points need not be adjusted for each of them.
- [x] Enable comments with a variable score. Example: the instructor
  wants to evaluate, among other things, the quality of the spelling
  in the student answers. He creates a (positive or negative) comment
  "Spelling" with a total number of points P. Then, when grading, the
  instructor enters a mark between `A` and `F` for the comment. The
  student will then get a score of P multiplied by a factor going from
  1 for `A` to 0 for `F` (reversed for negative comments).

**Comment by slel** [comment]
Regarding "Creating and editing comments", I would add:

- [ ] Allow editing an empty "Description" field

Indeed, it seems the Description field, if left empty, cannot later be edited.

**Comment by barais** [comment]
@slel Thanks, indeed, I will fix that

**Comment by barais** [comment]
@slel Fixed #387 . I add a simple edit button, close to the one for minimizing comments to edit all field of a comment including the void one

**Comment by nthiery** [comment]
Feedback from the current grading sessions: I'd say that the most important feature in the above list
is the ability to reorder the comments. I am spending a good chunk of the time
searching for the comments I want to select because they are in the somewhat random
order they were created in.

**Comment by nthiery** [comment]
Most of the randomness comes from me not knowing in advance which comment I will need :-)

**Comment by barais** [comment]
@nthiery For the moment, I remove randomness. I still have to implement the feature to let the teacher to reorder. For the moment, the order is the created order of comments.

**Comment by barais** [comment]
@nthiery I implement the default keyboard shortcut for all comments
https://github.com/correctexam/corrigeExamFront/pull/409

I will have a look this WE on the two issues you raise yesterday

**Comment by nthiery** [comment]
Thank you Olivier! I am looking forward my next grading session to enjoy all these features.

Hmm. Next grading session. Maybe not actually :-)
