### ISSUE TITLE
Import already annotated pdf's

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#341]
- [ ] Standardize how annotations (location of questions, comments, ...) could be embedded in pdf's
- [ ] Implement package(s) that enables annotating the source of the exam (e.g. LaTeX, Markdown, ...), and produce annotated pdfs, with automatic computation of the question location.

**Comment by barais** [comment]
- [ ] Partially exists without the scoring (see latex template)

**Comment by nthiery** [comment]
Ah, yes, right. Sorry for the noise. That's the trouble of doing things from memory a couple
 months later. It's actually on my side: I need to make the template work with my own exam template. Presumably, it will be about making the current correctexam class into a package.
I see that the pdf metadata is quite straightforward. So, when I'll eventually switch
from latex exams to markdown exams, I'll investigate writing a [myst](mystmd.org/) template.
