### ISSUE TITLE
Suggestions for the result view

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#342]
- [ ] Display the current total grade even if still incomplete; possibly with some visual feedback about this, like an orange background
- [ ] In addition to the total grade, display the grade for each question / group of question; typically with some folding UI to show more or less details

**Comment by barais** [comment]
Not sure to get these points. It is currently the case for the first action (in the table). 

For the second action, you have access to this view in the statistics

So I am not sure to understand the modification to apply  ?

**Comment by nthiery** [comment]
Ok; let's put this on hold; I don't remember myself the exact details
from when I took notes on that. It probably was about the copy view.
I'll keep that in mind during the upcoming grading, and take
screenshots if/when the need comes back.
