### ISSUE TITLE
Lien copie étudiant : la note n'apparaît pas

### ISSUE THREAD

**Issue by jgeandrot** [correctexam/corrigeExamFront#364]
Bonjour, 
après plusieurs tests, j'ai l'impression que la note de l'étudiant n'apparaît pas dans la page web qui lui permet de revoir sa copie.
Aussi, sur la version PDF de la copie corrigée, pas de note globale. 

Pourriez vous vérifier si c'est de mon côté seulement que cela ne marche pas.

Merci beaucoup. 
Julien Geandrot

![Capture d’écran 2023-10-11 à 11 06 06](https://github.com/correctexam/corrigeExamFront/assets/120249704/9c39a9ef-3722-4058-9944-17ecffccf1ef)

**Comment by jgeandrot** [comment]
Belle réactivité encore une fois. Merci et bravo !

**Comment by barais** [comment]
C'est à améliorer encore, car l'idée est de pouvoir sélectionner la zone où l'on met la note dans le pdf exporté. 

Tout est prêt côté modèle de données. Il reste à mettre la nouvelle icone dans la zone où l'on annote le pdf. 
Reste aussi à mettre le total et peut être laisser l'utilisateur finale décidé d'un total différent que la somme de notes de chaque question. Genre somme de chaque question sur 21 mais note = note sur 20 sans division. 

à voir
