### ISSUE TITLE
Keyboard short cut issue when navigating between exam sheets

### ISSUE THREAD

**Issue by sderrien** [correctexam/corrigeExamFront#388]
The CMD=left/right short cut does not behave as expected when navigating between exam sheets during grading. Instead of moving to the next/prev student, it moves to the next/prev question (just as CMD up/down).

**Comment by barais** [comment]
Really strange behavior. Code seems to be correct. 
https://github.com/correctexam/corrigeExamFront/blob/9e6065f1fcc6d70e27cc87f30b676a7fe5950ed6/src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts#L373C1-L374C1

I will try to test on macos to understand this issue. You are the second mac user that raise this issue. Thanks for the ticket.

**Comment by barais** [comment]
I just try to map keyboad to cmd + left and cmd + right

@sderrien Could you tell me if it is better ?

**Comment by sderrien** [comment]
CMD left/right now works as expected. 
Thks !

**Comment by barais** [comment]
Excellent, thanks for the feedback
