### ISSUE TITLE
Sclain student answer to fit frame width

### ISSUE THREAD

**Issue by sderrien** [correctexam/corrigeExamFront#391]
This issue arises when answers use a large portion of a page (say half of it). In such a situation answers do not fit within the browser frame (an easy workaround is to zoom out in the browser but then gui icons become too small to be managed).

**Comment by barais** [comment]
I guess, that you mean "fit frame height" So if the answer take half a page, you want to see it without vertical scrolling ?

**Comment by sderrien** [comment]
Yes, I meant frame height

**Comment by barais** [comment]
@sderrien I had on the left panel a way to select if you want to fit width, fit height or no scaling. Tell me if it is what you get in mind
