### ISSUE TITLE
Erreur nombre de copies / nombre d'étudiants

### ISSUE THREAD

**Issue by jgeandrot** [correctexam/corrigeExamFront#397]
Bonjour, 
je viens de finir de corriger mon premier examen avec CorrectExam, je suis agréablement surpris de l'utilisation, c'est très fonctionnel, je ne pourrais pas dire si je gagne du temps mais le retour à l'étudiant me semble très important, c'est ce que je privilégie. Et je vois que des fonctionnalités s'ajoutent au fur et à mesure (commentaires textuels avec zone de texte !).

Avant d'envoyer les résultats aux étudiants j'ai un problème concernant l'examen "Exam-MS-O-23-24" ; je pense que cela vient de la liste étudiants utilisée  et du nombre de copies scannées : pour faire des tests, je m'étais inclus dans la liste étudiant, mais dans l'examen réel ma copie n'apparaît pas. j'ai un état sur la correction de copies de 55 copies corrigées sur 56, mais cela dépend des questions ! Je n'arrive pas à régler le problème, j'ai peur de perdre toute la correction. 
Ce qui a été fait me semble bien fait, mais je ne peux pas réellement vérifier. Tout me semble OK dans le fichier Excel qui récapitule les résultats, comme prévu mon nom apparaît, alors que cela ne devrait pas pour cet examen (puisque pas de copies à mon nom).

Pouvez-vous m'aider ?

Merci beaucoup par avance.
Julien Geandrot

**Comment by barais** [comment]
Merci beaucoup pour ce retour. 
>  je ne pourrais pas dire si je gagne du temps mais le retour à l'étudiant me semble très important, 
Oui on est en accord sur l'objectif ;). 

Pour le petit problème, je regarde. Souvent, c'est lié à un problème à l'affectation des étudiants.

**Comment by barais** [comment]
C'est fixé;

**Comment by jgeandrot** [comment]
C'est parfait, le retour est ultra rapide, c'est super ! merci beaucoup. Malgré la seule expérience si je peux témoigner positivement pour votre travail, je le ferai volontiers.
