### ISSUE TITLE
Where to send student requests

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#401]
Currently, when a student makes a request about his copy, the request is
sent by email to the exam owner. When grading in team, the owner then
has to manually forward the email to the person having graded that
question.

Suggestion: send instead the email to the whole team at once:
- Best: send it to the person(s) who corrected the question (if that information is modeled in the database), with the rest of the team in CC.
- Second best: send it to the exam owner with the rest of the team in CC

In the long run, it would be ideal to have a mini discussion forum per student/question
directly in the app, with email notifications to the exam owner + question grader. This
would make it easier to track and navigate questions and answers.

**Comment by barais** [comment]
I will probably implement the second best for the moment. I did not keep any traceability information regarding who did the correction of a specific answer. So, I will do first second proposition and keep the best as a TODO for a future version.

**Comment by nthiery** [comment]
Thank you!
