### ISSUE TITLE
Feedback view: add a link to the correction view for instructors (feature request)

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#402]
Scenario: a student follows the feedback link browse his graded copy,
and has a question about how a given question was graded. He sends
an email to the instructor. The instructor realizes that there is an error
(or needs to double check something) and wants to switch to the correction
view.

Proposition 1: if the viewer is logged in and is an instructor for this exam, then a
  direct link to the correction view is added.
Proposition 2: add a button "I am instructor; open the correction view" that brings
the viewer through authentication to the correction view.

**Comment by barais** [comment]
Yes, I will implement proposition 1. Two lines of code ;)
