### ISSUE TITLE
Student result view: students appearing twice (bug)

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#408]
In the student result view of my exam, many students (like A. V.) appear twice.
The various links (to pdf, feedback view, ...) are identical, but not the score.

@barais: you can access the view here:

https://correctexam.github.io/corrigeExamFront/showresults/186

**Comment by barais** [comment]
@nthiery 

I fix it for your exam but i will let the bug open. Indeed, I add a notion of FinalResult in DB that keep the note for one student and one exam. (It is computed each time). I do not known why but several "Finalresult" have been created for the same exam and the same student. Not a big deal as it is a computed value, I can delete them but It should never happen. I will review the code to find the bug and add a constraint in the database.

**Comment by barais** [comment]
done for the constraints
