### ISSUE TITLE
Opening the "show results" page takes about 15s for 234 copies

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#414]
The title says it all :-)

No urgency at all; it's still perfectly usable. Just surprising when
opening the grading view is essentially instant.

Steps to reproduce: @barais: you have the link to my Info111 course.

**Comment by barais** [comment]
I improve the performance

**Comment by nthiery** [comment]
Excellent, much faster indeed: about 3s which is totally fine for such
a page that is not accessed repeatedly.
