### ISSUE TITLE
Bug sur "Comparaison des copies avec même commentaire"

### ISSUE THREAD

**Issue by VivianePons** [correctexam/corrigeExamFront#438]
Bonjour,

quand je veux afficher les copies avec un même commenaire, j'ai l'impression que ce sont les bonnes copies mais avec la mauvaise note

Sur l'image ci-dessous, ce sont bien des copies à qui j'ai mis le commentaire mais qui ont comme note 1/6 (et pas la note affichée)

Par ailleurs, le commentaire est affiche avec +0.25 alors que c'est un commentaire à +1point

![Capture d’écran du 2023-12-18 18-19-08](https://github.com/correctexam/corrigeExamFront/assets/3606240/061b8702-ec90-4a5c-b1a1-65507e407f14)

Voilà le lien vers l'exo en question

https://correctexam.github.io/corrigeExamFront/comparehybridcomment/235/179/1

**Comment by barais** [comment]
Merci bcp pour ce retour très clair, 
c'est clairement un bug, j'ai ajouté la notion de question hybrid un peu rapidement. Je corrige cela au plus vite.
