### ISSUE TITLE
Default comment for negative grading

### ISSUE THREAD

**Issue by sderrien** [correctexam/corrigeExamFront#466]
From my understanding, in the case of a negative correction scheme, it is not possible to know whenever a student question was graded as 100% correct or was simply being passed over without grading action. 

If this is indeed the case, It would be useful to add a default comment that the user will have to check on to indicate that the question can be considered as graded.

**Comment by barais** [comment]
It exists. When you create annotate the template, you have a button to manage comment and add  default comments. Within this comment, there is one which is ok, (not excellent), that put the question as graded
