### ISSUE TITLE
Suggestions for the student view

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#471]
- Currently the number of points for the exercise is displayed as `Note attribuée: 4`; I suggest to add the maximal number of points; for example: `Note attribuée: 4/6`. Maybe also add 'pt' for consistency with the comments.
- For comments with a number of points of 0: displaying it as `0 pt` is ambiguous: does the comment set the total number of points to 0, or contribute 0 points to the total? Suggestion: use e.g. `+0 pt`.

**Comment by nthiery** [comment]
Thanks for that early Sunday gift :-) Works smoothly!

Just a tiny note: it seems like the spacing for positive and negative grades is different: "+ x" versus "-x". Not that it matters much :-)

**Comment by barais** [comment]
I fix that. It is currently redeploying with also a new feature #476
