### ISSUE TITLE
Can we imagine having an export for the global modules instead of one for each exam?

### ISSUE THREAD

**Issue by jbourcie** [correctexam/corrigeExamFront#475]
I am running a module where I make small exams at the end of each session. I can only export results from within each exam. It would be great to have a way to export the module with all exams...

**Comment by barais** [comment]
+1

**Comment by barais** [comment]
@jbourcie If you could test the two feature ABJ and export grade for a complete module during your next exam and let me know if it fits your requirements

**Comment by jbourcie** [comment]
The csv export works. The excel one does not work !
