### ISSUE TITLE
Navigation between questions during correction : A possiblity to iterate over all questions from all students  with one button

### ISSUE THREAD

**Issue by LFLCH** [correctexam/corrigeExamFront#48]
During correction, once arrived to the last question, the right button is disabled. I think it could be great if it would permit go back to the first question. Likewise with the student navigation. 
A nice thing would be that when arrived to the last question, the next page would be the first question of the next student. 
Likewise when arrived to the last student : the next page would be the first student at the next question.

To be clearer, I made this diagram : 
![image](https://user-images.githubusercontent.com/62034725/178540353-8925be3f-d898-4100-8f76-d57921a64896.png)

**Comment by barais** [comment]
@arnobl  What do you thing regarding usability. 

If you agree I could implement it

**Comment by arnobl** [comment]
I do not know. It may be interesting but the fact that 'next student' moves to the next question at a moment is disturbing. 
When moving to the next question using the button 'next question', I suggest to rename the button accordingly. Same thing for the button 'next question' that at the end moves to the next student.

**Comment by barais** [comment]
done with keyboard shortcut only
