### ISSUE TITLE
Bug - broken grading summary interface

### ISSUE THREAD

**Issue by bloa** [correctexam/corrigeExamFront#495]
**Screenshot:**
![2024-02-23-144550_1604x204_scrot](https://github.com/correctexam/corrigeExamFront/assets/48352751/22c78656-bcb4-432c-b0fa-cf5e63c91bb3)

I apparently managed to grade 31 copies despite only having 20 students.
The two "Recheck/Continue" and "Show all" buttons are also missing from the DOM.
The issue isn't just cosmetic and persists after reloading the page using F5.

**Comment by barais** [comment]
Bad bug I did a mistake, I remove an integrity constraint and it is bad news as it allow you to create two answer correction for the same question/sheet. I will correct it.

**Comment by barais** [comment]
correct
