### ISSUE TITLE
Bug: broken button for switching between raw and normalised statistics

### ISSUE THREAD

**Issue by bloa** [correctexam/corrigeExamFront#496]
**Correct behaviour:** when using CorrectExam **_in French_**, the statistics page displays a graph with normalised grade values.
The "changer la vue" button correctly switch back and forth between using normalised and raw values.

**Bug:** when using CorrectExam **_in English_** instead, the statistics page first displays the graph with raw values, and the "change the view" button is the one-way only to switch to normalised values (you can't switch back to raw values anymore).

**Suggested fix:** fix the switch button and mimic the French page by starting with normalised values (it feels more useful that way?)

**Comment by bloa** [comment]
This line seems suspicious: https://github.com/correctexam/corrigeExamFront/blob/133f512e8aabf0d6bc40cba9aac456c473988dd6/src/main/webapp/app/scanexam/statsexam/statsexam.component.ts#L516

Shouldn't the literal strings "pourcents" and "brut" be subject to i18n interpolation? Like in https://github.com/correctexam/corrigeExamFront/blob/133f512e8aabf0d6bc40cba9aac456c473988dd6/src/main/webapp/app/scanexam/statsexam/statsexam.component.ts#L528

In any case, storing the state of the radar using i18n strings seems... ill advised, wouldn't using an Enum be better?

**Comment by barais** [comment]
Thanks you find the bug and find the fix ;).
