### ISSUE TITLE
Bug - Broken page titles

### ISSUE THREAD

**Issue by bloa** [correctexam/corrigeExamFront#499]
**Bug:** In some occasions page titles are incorrectly rendered, for example after switching language.

**Screenshot:**
![2024-03-04-141014_1920x1200_scrot_crop](https://github.com/correctexam/corrigeExamFront/assets/48352751/3d37f4a7-87b3-414a-815d-7681313b3105)
In this case this is the statistics page but the bug seems to affect pretty much all pages.

**Steps to reproduce:**
- Open any page with a dynamic title.
- The title is initially correct (e.g., "`Exam CC du cours ALA2023`")
- Change language from FR to EN, or EN to FR.
- The title is now broken (e.g., "`Exam: {{examName}} for course {{courseName}}`"

**Comment by barais** [comment]
Excellent, just fix it. It should be better after the next deployment
