### ISSUE TITLE
Problème d'accès liens prof/élève/copies pdf annotées

### ISSUE THREAD

**Issue by jgeandrot** [correctexam/corrigeExamFront#509]
Bonjour, 
J'ai utilisé correct exam pour mon dernier examen. J'en suis toujours ravi, ce deuxième test m'a montré comme votre appli était efficace. Merci pour ça.

Par contre j'ai un petit souci depuis que j'ai fini la correction : je n'arrive pas, depuis la page "résultats étudiants", à accéder aux différents liens. J'ai essayé sur plusieurs navigateurs sans succès. J'attends cela pour vérifier quelques copies annotées avant d'envoyer un mail aux étudiants.

Je vous remercie beaucoup par avance.
Julien Geandrot

**Comment by barais** [comment]
Désolé, régression dans la config de déploiement. J'ai corrigé, cela devrait être ok dans 10 minutes

**Comment by jgeandrot** [comment]
Bonjour Super, merci et merci toujours pour la réactivité.Bon week endJulien GeandrotLe 15 mars 2024 à 20:21, Barais ***@***.***> a écrit :﻿
Désolé, régression dans la config de déploiement. J'ai corrigé, cela devrait être ok dans 10 minutes
