### ISSUE TITLE
Migrate comments when changing grading scale.

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#515]
Use case: @hivert started to grade a question using a "direct" grading scale. At some point he
realized that an "hybrid" grading scale would be more appropriate. When changing
the grading scale however, all comments dissapeared, both from the comment list and
the student copies; which scared a bit @hivert. Gladly, they were still in the database, and
reappeared when switching back to a direct grading scale :-)

Would it be possible instead to migrate the comments when changing from one scale to the other?
If there is some loss of information, like how many points are attached to a comment, that's
presumably ok, especially if there is a warning about it.

**Comment by barais** [comment]
> Use case: @hivert started to grade a question using a "direct" grading scale. At some point he
realized that an "hybrid" grading scale would be more appropriate.
Yes changing the type of grading during a scoring session is not supported. Migrating the comments is possible.  I think the best option in the future is to match everything on the hybrid model. It can possibly unify everything.

As a patch, I will add the ability to go from direct or postive/negative to hybrid but not in the other way. For positive/negative to hybrid, I can keep the scoring. For direct, I will add a new hybrid comment called score with step and grade to keep the grade. I will keep all textcomment to hybrid comment with score to 0%

**Comment by nthiery** [comment]
Thanks for the quick feedback! Yes direct->hybrid migration will do very well for now.
