### ISSUE TITLE
Edit field for the long description of a comment

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#516]
The field for editing the long description of a comment used to be (IIRC) a texte area,
allowing in particular for multiline comments. This was handy for long descriptions, to
have multiple paragraphs, itemized lists, etc. It also can make navigation faster with
up/down arrow key strokes.

It seems that the field has been made into a simple one line text field. Regression?
Deliberate choice to reduce vertical space?

Btw: on Florent's machine (ubuntu/firefox) keystroke repetition by holding the key
pressed was disabled. Which makes navigation with left/right arrows painful.

**Comment by barais** [comment]
@nthiery . I change that, 
it is more a regression than a feature
