### ISSUE TITLE
Changes to comments improperly inserted in the database.

### ISSUE THREAD

**Issue by nthiery** [correctexam/corrigeExamFront#549]
While grading the other day on [this exam](https://correctexam.github.io/corrigeExamFront/exam/annotate/381) I encountered the following incorrect behavior:

1.  In the annotation tab, I imported the default comments in Question 4. These comments then appeared as expected in the UI; but then vanished after leaving the annotation tab. I tried again a couple times without more success. On the other hand, I discovered later that Question 2 had many copies of these comments, presumably from all the attempts. This sounds like an index error while inserting the data in the database.
2.  On several occasions, in the grading tab, I tried to change the percentage associated with a given comment (e.g. for "Erreur de syntaxe"). Again, this was reflected as expected on the UI; but later the change vanished when switching to another question and back. Again, this sounds like the change was not inserted into the database.

**Comment by barais** [comment]
@nthiery Just to be sure on the scenario for the first problem. You saved the comment in json from Q2 and your rimport from JSON in Q4? Right ?

**Comment by nthiery** [comment]
Well done :-) Thank you!
Feel free to ask for more details if you have trouble reproducing; my report is indeed not as precise as desirable.
For confirmation: it was through "sauvegarder commentaires par défaut / ajouter commentaires par défaut".

**Comment by nthiery** [comment]
Thank your @barais !

**Comment by barais** [comment]
You're welcome, thanks a lot for the accurate feedback. Two bugs that were hidden only for hybrid comments ;). We have to improve the test suite for hybrid comment.
