### ISSUE TITLE
Bug — normalised grades > 100% and broken gauge plots

### ISSUE THREAD

**Issue by bloa** [correctexam/corrigeExamFront#565]
Some of the questions from my latest exam appear incorrectly on the statistics page.
Specifically, their normalised values exceed 100%, reaching up to 300%, although individual grades for those questions ("correct exam sheets" -> "show all") seem correct.

Additionally, the corresponding gauge plots (identical for both raw/normalised values) appear graphically broken:
![2024-10-15-150827_263x155_scrot](https://github.com/user-attachments/assets/4186ceae-2136-4285-a0de-00d8f600be1b)

CorrectExam IDs: course#268, exam#478

**Comment by barais** [comment]
Yes, I will fix that. 

You used a lot the new hybrid grades. You are right. Probably we do not test sufficiently the statitic pages with this notation type.

**Comment by bloa** [comment]
I can still see broken gauges in the per-student view (as well as an empty plot at the end... off-by-one?)

![2024-10-17-181656_835x307_scrot](https://github.com/user-attachments/assets/94a28050-4b3d-4c38-beaf-b2b47e91e1b3)

**Comment by barais** [comment]
Ok, I reopen

**Comment by bloa** [comment]
More bugs:

- a typo in src/main/webapp/app/scanexam/statsexam/statsexam.component.ts : https://github.com/correctexam/corrigeExamFront/blob/main/src/main/webapp/app/scanexam/statsexam/statsexam.component.ts#L597
- radar chart do not skip skipped questions (in the screenshot: no grade for questions 6 and 8)
- some percentages still > 100% (here, 340%; probably just related to the skipped questions)

![2024-10-23-133856_1163x984_scrot](https://github.com/user-attachments/assets/30e0adf5-1aed-4675-aa59-850c5336bf04)

Additionally, in the gauge chart below, shouldn't the values change between raw and normalised views? (they always show raw grades)
