### ISSUE TITLE
Should the app lock the whole screen just after selecting a mark?

### ISSUE THREAD

**Issue by arnobl** [correctexam/corrigeExamFront#7]
When marking a question (using the sliders or by clicking on stars), the screen is locked while the REST query operates (for a very short time in general, but may be long on server lags).

Maybe we should remove this lock. Does this lock prevent any side-effect?

**Comment by arnobl** [comment]
```ts
  changeNote(): void {
    if (this.resp !== undefined) {
      this.blocked = true;
      this.resp!.note = this.currentNote;
      this.studentResponseService.update(this.resp!).subscribe(sr1 => {
        this.resp = sr1.body!;
        this.blocked = false;
      });
    }
  }
```

This is the code related to the issue. The single reason for blocking the UI is getting the body of the answer: `this.resp = sr1.body!;`. But is that really necessary to update the current student?

**Comment by barais** [comment]
Yes I did it as sometimes, I had this impression that rest API failed and we miss the information

**Comment by barais** [comment]
improve performance on that part
